name: 'Release with Changelog'
icon: 'tag'
branding:
  icon: 'tag'
  color: 'purple'
description: 'Create a GitHub relase with changelog for every tag you push'
inputs:
  tag:
    description: Specific tag to generate changelog against
    required: false
  token:
    description: Personal access token (PAT) used to create releases
    required: true
  include-hash:
    description: Prepend and link commit hash to each entry
    required: false
    default: false
  include-range:
    description: Adds a compare link between tags at end of release roles
    required: false
    default: true
  header:
    description: Content to prepend at the start of release notes
    required: false
    default: ''
  footer:
    description: Content to append at the end of release notes
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'distribution/index.js'
